monolog:
  channels: ['axytos.kauf_auf_rechnung.plugin.channel']

  handlers:
    myPluginLogHandler:
        type: rotating_file
        path: "%kernel.logs_dir%/my_plugin_%kernel.environment%.log"
        level: error
        channels: [ "axytos.kauf_auf_rechnung.plugin.channel"]