monolog:
  channels: ['axytos.kauf_auf_rechnung.plugin.channel']

  handlers:
    myPluginLogHandler:
        type: rotating_file
        path: "%kernel.logs_dir%/axytos_kauf_auf_rechnung_%kernel.environment%.log"
        level: info
        channels: [ "axytos.kauf_auf_rechnung.plugin.channel"]